### ISSUE TITLE
用于Archlinux的AUR安装

### ISSUE THREAD

**Issue by 4679** [coyove/chann#1]
https://aur.archlinux.org/packages/chann-git/
随手写了一个 方便自己(=ﾟωﾟ)=

**Comment by coyove** [comment]
4679，莫非是高中生PO

**Comment by 4679** [comment]
(´ﾟДﾟ`)这都能认出来

**Comment by coyove** [comment]
高中生好好学习啦上什么同性网站| ω・´)

**Comment by 4679** [comment]
垃圾网站 毁我青春 教我搞基(;´Д`)
